Add frontend code to allow user interaction
cs340-illinois/pixel-board-shared-middleware pull request #7
Opened 2022-11-30 00:39 UTC by xinze-zheng

# Overview
The modification allows users to update the board via frontend in a timely(3 seconds rate-restriction by default) manner. #2 

# Modification details
**app.py**: Add route `'/changeByClick/<r>/<c>/<color>/<id>/'`. Frontend will send request via this route to update the board.

**FrontendManager.py**: The app.py mantains a gloabl instance of this class. This class will be invoked when there is a frontend update reqeust and this class will check the timestamp between updates and the secret code.

**index.html**: Some changes for UI.

**css.css**: Some changes for styling.

**pixelboard.js**: Add eventlistener for canvas, function for initializing color selector and initializing secret textfield.

<img width="349" alt="image" src="https://user-images.githubusercontent.com/112009367/204677423-11afe959-fbff-48cc-9af6-de62052129a8.png">

2022-11-30 22:33 UTC, wadefagen requested changes
Everything looks amazing -- except exactly how the request is impl'd in the middleware.  See the code comment.  If you can fix that, it'll be ready to merge!

2022-11-30 22:33 UTC, wadefagen commented on app.py
> +    return result
To keep this in the same style as the rest of this API, can you update this to move the parameters from the URL to JSON, and make it a `PUT` or `POST`?

Since it's modifying the content a `GET` doesn't make sense here.

2022-12-01 01:43 UTC, xinze-zheng commented on app.py
> +    return result
Oops, thank you for your advice. I used my old api which is indeed very different to the style of other routes. I will update the PR very soon😃.

2022-12-01 02:36 UTC, xinze-zheng commented
The route is changed to POST with the documentation in README.md as shown below.

---

**POST** `/changeByClick`

This route receives a json file from the frontend and updates the pixel.

Request Data: JSON containing the keys `"secret"`, `"row"`, `"col"` and `"color"`. The `"secret"` string can be any value right now, but must be present.

Response Status Codes: If the update is successful, a `200 Success` is sent. If the update is successful, a `400 Too frequent update` is sent. If the json file is missing, a `401 No json file` is sent. If the required field in the json file is missing, a `402 Missing attributes` is sent.

**Note:** The FrontendManager is responsible for checking the timestamp and secret for the requst. The required request interval can be changed by changing the constant `time_gap` which is set to 3 seconds by default.

2022-12-01 21:49 UTC, wadefagen commented
LGTM! :tada:

2022-12-01 21:49 UTC, merged